name: AppleScript Compilation

on:
   workflow_dispatch:
     inputs:
      inputFile:
        description: 'The file to compile'
        required: true
        default: 'input.applescript'
        type: string
      outputFile:
        description: 'The compiled file'
        required: true
        default: 'output.scpt'
        type: string

jobs:
   build:
      runs-on: macos-latest

      steps:
      -  name: Clone repository
         uses: actions/checkout@v4

      -  name: Compile AppleScript
         run: osacompile -o "${{ github.event.inputs.outputFile }}" "${{ github.event.inputs.inputFile }}"

      -  name: Upload compiled AppleScript
         uses: actions/upload-artifact@v2
         with:
            name: ${{ github.event.inputs.outputFile }}
            path: ${{ github.event.inputs.outputFile }}
