name: AppleScript Decompilation

on:
   workflow_dispatch:
     inputs:
      inputFile:
        description: 'The file to decompile'
        required: true
        default: 'input.scpt'
        type: string
      outputFile:
        description: 'The decompiled file'
        required: true
        default: 'output.applescript'
        type: string

jobs:
   build:
      runs-on: macos-latest
      env:
         inputFile: ${{ github.event.inputs.inputFile }}
         outputFile: ${{ github.event.inputs.outputFile }}

      steps:
      -  name: Clone repository
         uses: actions/checkout@v4

      -  name: Compile AppleScript
         run: osadecompile "${inputFile}" > "${outputFile}"

      -  name: Upload compiled AppleScript
         uses: actions/upload-artifact@v2
         with:
            name: ${{ github.event.inputs.outputFile }}
            path: ${{ github.event.inputs.outputFile }}
